docker:
  - image: cimg/node:16.13
    auth:
      username: $DOCKERHUB_USER
      password: $DOCKERHUB_PASSWORD
working_directory: ~/kubernetes-monitor
steps:
  - checkout
  - install_python_requests

  - run:
      name: Deploy to dev
      command: ./scripts/circleci-jobs/deploy_to_dev.sh

  - run:
      name: Notify Slack on failure
      command: ./scripts/slack/notify_failure.py "${CIRCLE_BRANCH}" "${CIRCLE_JOB}" "${CIRCLE_BUILD_URL}" "${CIRCLE_PULL_REQUEST}" "${SLACK_WEBHOOK}"
      when: on_fail
