machine:
  resource_class: large
  # https://circleci.com/developer/machine/image/ubuntu-2204
  image: ubuntu-2204:current
  docker_layer_caching: true
working_directory: ~/kubernetes-monitor
steps:
  - checkout
  - setup_node16
  - install_python_requests
  - run:
      name: create temp dir for logs
      command: mkdir -p /tmp/logs/test/integration/openshift4
  - run:
      name: Integration tests OpenShift 4
      command: |
        export OPERATOR_VERSION="0.0.1-ubi8-${CIRCLE_SHA1:0:8}"
        export IMAGE_TAG_UBI_SUFFIX="-ubi8"
        export KUBERNETES_MONITOR_IMAGE_NAME_AND_TAG=$(./scripts/circleci-jobs/setup-integration-tests.py)
        .circleci/do-exclusively --branch staging --job ${CIRCLE_JOB} npm run test:integration:openshift4:operator
  - run:
      name: Notify Slack on failure
      command: |
        ./scripts/slack/notify_failure_on_branch.py "${CIRCLE_BRANCH}" "${CIRCLE_JOB}" "${CIRCLE_BUILD_URL}" "${CIRCLE_PULL_REQUEST}" "${SLACK_WEBHOOK}"
      when: on_fail
  - store_artifacts:
      path: /tmp/logs/test/integration/openshift4
